# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.5
services:
  - postgresql
before_script:
  - psql -c 'create database wordfor_test;' -U postgres
  - psql -c "create role wordfor with password 'wordfor123';" -U postgres
install: pip install -r requirements/dev.txt
script: python manage.py test
