"""Creates the searches table.

Revision ID: 00f27e7856c7
Revises: 40f157c649de
Create Date: 2016-09-25 15:48:29.013203

"""

# revision identifiers, used by Alembic.
revision = '00f27e7856c7'
down_revision = '40f157c649de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=70), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searches')
    ### end Alembic commands ###
