"""Creates the words, definitions, answers relations and their relationships to each other and searches.

Revision ID: 2ae439b689d5
Revises: 00f27e7856c7
Create Date: 2016-09-25 17:13:32.295230

"""

# revision identifiers, used by Alembic.
revision = '2ae439b689d5'
down_revision = '00f27e7856c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'search_id')
    )
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('searches', 'answer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('answer', sa.VARCHAR(length=70), autoincrement=False, nullable=True))
    op.drop_table('definitions')
    op.drop_table('answers')
    op.drop_table('words')
    ### end Alembic commands ###
