"""Changes the 'part_of_speech' column to be named 'word_class' in definitions.

Revision ID: 634731ff04c2
Revises: 2ae439b689d5
Create Date: 2016-09-25 17:37:24.348820

"""

# revision identifiers, used by Alembic.
revision = '634731ff04c2'
down_revision = '2ae439b689d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('word_class', sa.String(), nullable=False))
    op.drop_column('definitions', 'part_of_speech')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('part_of_speech', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('definitions', 'word_class')
    ### end Alembic commands ###
