"""Update searches.query to be searches.query_string

Revision ID: 9afd0d661320
Revises: db9cebab6ff7
Create Date: 2016-09-28 23:23:44.470480

"""

# revision identifiers, used by Alembic.
revision = '9afd0d661320'
down_revision = 'db9cebab6ff7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_search_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'searches', ['search_id'], ['id'])
    op.add_column('searches', sa.Column('query_string', sa.String(length=200), nullable=False))
    op.drop_column('searches', 'query')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('query', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('searches', 'query_string')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_search_id_fkey', 'answers', 'words', ['search_id'], ['id'])
    ### end Alembic commands ###
